### PR TITLE
Add new default mail template and extend from it in all mails we use

### PR DESCRIPTION
**Pull request by Katrienvh**
## Type

- Enhancement

## Pull request description

Override the default mail template in our theme and change the markup so we can paste the markup from the foundation mail tool

### CODE REVIEW

**Comment by carakas** [comment]
https://github.com/sumocoders/forkcms/blob/1c7be40036dda5ddd66b9cc601bf9b1d3b54b5b8/src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig#L25 margin shouldn't be with a capital M

**Comment by mathiashelin** [comment]
Yes, it should be with capital M for some specific mail clients.

**Comment by mathiashelin** [comment]
https://github.com/sumocoders/forkcms/blob/4d94d59266bb6464ce7919f7ac399b6d375f91ec/src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig#L10
Zou je dit niet beter door SiteTitle vervangen?

**Comment by mathiashelin** [comment]
https://github.com/sumocoders/forkcms/blob/4d94d59266bb6464ce7919f7ac399b6d375f91ec/src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig#L1409
Zou ik weglaten

**Comment by mathiashelin** [comment]
https://github.com/sumocoders/forkcms/blob/4d94d59266bb6464ce7919f7ac399b6d375f91ec/src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig#L1404
Is dit relevant?

**Comment by mathiashelin** [comment]
https://github.com/sumocoders/forkcms/blob/4d94d59266bb6464ce7919f7ac399b6d375f91ec/src/Frontend/Themes/Bootstrap/src/Layout/Templates/Mails/Default.html.twig#L1444
Is hier al een default image voor?

**Comment by mathiashelin** [comment]
:shipit:

**Pull request merged**
