### PR TITLE
Forbid access to the .git folder

### PR DESCRIPTION
**Pull request by tijsverkoyen**

### CODE REVIEW

**Comment by WouterSioen** [comment]
This should probably be pull requested to forkcms/forkcms?

**Comment by tijsverkoyen** [comment]
It could be, but for Fork itself it isn't a real issue, because in most cases the .git-folder won't be present at the production-server. But for Sumo we use deployment and the .git-folder can be available.

**Comment by tijsverkoyen** [comment]
I will create a separate PR

**Comment by WouterSioen** [comment]
:+1: :shipit:

**Pull request merged**
