### PR TITLE
Set debugmode to true on staging-server

### PR DESCRIPTION
**Pull request by tijsverkoyen**
Because the robots-meta-tag is only inserted when debug is true, we need debug
to be true on the staging-server.

We can't solve this with ENV-variables because they aren't passed due a
documented issue with suExec and mod_env, see http://wiki.dreamhost.com/Suexec#Apache_module_mod_env
for more information.

### CODE REVIEW

**Comment by WouterSioen** [comment]
Note to self: this will also force us to install dev dependencies when deploying.

**Comment by WouterSioen** [comment]
If you only want debug mode true because of the robots-meta-tag, i'd add the check there.

This would enable the robots meta tag on the server, but still serve the site in production mode.

I think it's still best to server the full site in production mode, to keep it as close to production as possible.

**Comment by tijsverkoyen** [comment]
Fixed in 2e4c4fd4f382d9f0e834a1ae38d777606a88588c

**Comment by WouterSioen** [comment]
I think this is good to go after squashing the commits.

**Comment by tijsverkoyen** [comment]
Cherry-picked the latest commit in the master, as rebase doesn't allow reverts to be squashed.

**Comment by WouterSioen** [comment]
:+1:

**Pull request closed without merging**
